### ISSUE TITLE
CLI is untested for Bash 3.2

### ISSUE THREAD

**Issue by marcusrossel** [WalkingPizza/arduino-light-show#5]
I use Bash 5.0.2 while macOS has Bash 3.2 by default. The testing I have done is therefore only mildly sufficient. 
Therefore, could @Nosp1 do the following tests in a macOS terminal?

---

### 1:
 Run `bash --version` in a terminal. If the version is 3.2 (or at least less than 5.0), do tests 2 and 3.

---

### 2:
Run
```
cd ~/Desktop; curl -sSfL 'https://raw.githubusercontent.com/WalkingPizza/arduino-light-show/master/Command%20Line%20Interface/Installation/installer.sh' | bash
```
and post the output in this issue.

---

### 3:
Clone this repository, navigate to the `Tests` folder, run `./run_tests.sh` and post the output in this issue.

Thanks.

**Comment by marcusrossel** [comment]
@Nosp1 could you run

```
cd ~/Desktop; bash --version; curl -sSfLO 'https://raw.githubusercontent.com/WalkingPizza/arduino-light-show/master/Command%20Line%20Interface/Installation/install_files'; curl -sSfL 'https://raw.githubusercontent.com/WalkingPizza/arduino-light-show/master/Command%20Line%20Interface/Installation/installer.sh' | bash
```

in a terminal and post the output here?

**Comment by Nosp1** [comment]
Yo, saw this now

Here is the input and output from terminal on Windows, want me to run it on a mac?


$ cd ~/Desktop; bash --version; curl -sSfLO 'https://raw.githubusercontent.com/W

alkingPizza/arduino-light-show/master/Command%20Line%20Interface/Installation/in

stall_files'; curl -sSfL 'https://raw.githubusercontent.com/WalkingPizza/arduino

-light-show/master/Command%20Line%20Interface/Installation/installer.sh' | bash

GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

Copyright (C) 2016 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later



This is free software; you are free to change and redistribute it.

There is NO WARRANTY, to the extent permitted by law.

curl: (22) The requested URL returned error: 404 Not Found

The Arduino Light Show installer requires Git. Please install it first.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by marcusrossel** [comment]
@Nosp1 please test again...

**Comment by Nosp1** [comment]
Performed step 1) bash version 3.2.57. 

Performed step 2) Error: Arduino CLI installation failed. See attached files


![Screenshot 2019-03-19 at 13 43 42](https://user-images.githubusercontent.com/13243486/54606976-7c4eff80-4a4d-11e9-9823-2d9b93c9c247.png)


Performed step 3) All tests passed. See attached files

![Screenshot 2019-03-19 at 13 46 10](https://user-images.githubusercontent.com/13243486/54607007-8f61cf80-4a4d-11e9-8858-192b47334e26.png)

**Comment by dtpett16** [comment]
Moving arduino-cli (or anything else) into /usr/local/bin requires administrative permissions. Try running the script as sudo.

**Comment by Nosp1** [comment]
Test 2: tried to use Sudo on installation. Got return message: It seems you already have run this installation. tried to reinstall, but bash does not find command y or n. See screenshot.
![Screenshot 2019-03-19 at 14 46 16](https://user-images.githubusercontent.com/13243486/54610672-c3d98980-4a55-11e9-98da-f451272de6d4.png)

**Comment by dtpett16** [comment]
Interesting. Could "yes" or "no" maybe work? If I have time I'll have a short look at the script.

**Comment by Nosp1** [comment]
> Interesting. Could "yes" or "no" maybe work? If I have time I'll have a short look at the script.

Tested "yes" instead of "y". Resulted in yes looping till I stopped it with cntrl + C

**Comment by marcusrossel** [comment]
mhh ok thats not cool 😅

**Comment by marcusrossel** [comment]
Ok, should be fixed.
@Nosp1 please retest...

**Comment by Nosp1** [comment]
> Ok, should be fixed.
> @Nosp1 please retest...

Tested step 2 again)  with sudo and without. same result y & n does not work.
![image](https://user-images.githubusercontent.com/13243486/54676040-12dbf900-4b00-11e9-93cc-d40d7f5430f8.png)

**Comment by marcusrossel** [comment]
Turns out I was using Bash 3.2.57 the whole time, as brew doesn't install it in `/bin`. This issue is therefore redundant.
